export const SET_SEARCHED_HITTERS = 'SET_SEARCHED_HITTERS';
export const ADD_HITTER = 'ADD_HITTER';

//Navigation
export const SET_TAB = 'SET_TAB'

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'