---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: xaethos/android-build
    tag: no-sdk


inputs:
  - name: android-sdk-linux
  - name: npm-resource-container

outputs:
  - name: build-output

run:
    path: sh
    args:
      - -euxc
      - >-
        TERM=screen-256color
        ANDROID_HOME="$PWD/android-sdk-linux"
        cp npm-resource-container/license $ANDROID_HOME/
        npm-resource-container/android/gradlew --project-dir=npm-resource-container/android :assembleDebug --stacktrace
