---
jobs:
  - name: build-mobile-apk
    plan:
    - get: android-sdk-linux
    - get: mobile-repo
      trigger: true
    - task: npm-install
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
              repository: node
          inputs:
            - name: mobile-repo
          run:
            path: mobile-repo/ci/tasks/install.sh
    - task: assemble-app
      file: mobile-repo/ci/tasks/assemble.yml

resource_types:
  - name: android-sdk
    type: docker-image
    source: {repository: xaethos/android-sdk-resource}

resources:
  - name: android-sdk-linux
    type: android-sdk
    source:
      components:
        - android-23
        - build-tools-23.0.2
        - extra-android-m2repository
  - name: mobile-repo
    type: git
    source:
      uri: {{GIT_REPO}}
      branch: {{GIT_BRANCH}}
      private_key: {{GIT_PRIVATE_KEY}}
